title: Hong's Blog  # 博客标题
description: 本分健康，认真努力。做对事情，知错即止。  # 博客描述
baseurl: "/hong525"

# 使用远程主题
remote_theme: riggraz/no-style-please

# 插件
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# 主题特定配置
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

favicon: "logo.jpeg"
   
